name: Deploy Streamlit App to Azure
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel setuptools
        pip install -r requirements.txt
    
    - name: Create .env file from GitHub Secrets
      run: |
        echo "$APP_SECRETS" > .env
      env:
        APP_SECRETS: |
          AZURE_BLOB_CONNECTION_STRING=${{ secrets.AZURE_BLOB_CONNECTION_STRING }}
          AZURE_AI_ENDPOINT=${{ secrets.AZURE_AI_ENDPOINT }}
          AZURE_AI_KEY=${{ secrets.AZURE_AI_KEY }}
          AZURE_MODELS_ENDPOINT=${{ secrets.AZURE_MODELS_ENDPOINT }}
    
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Stop existing deployment
      run: |
        az webapp stop --name safewatch --resource-group your-resource-group
      
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'safewatch'
        slot-name: 'production'
        package: '.'
      
    - name: Start webapp
      run: |
        az webapp start --name safewatch --resource-group your-resource-group
